services:
    postgres:
        image: postgres:15.1
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 54328:5432
    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - postgres
    web:
        build:
            context: .
            dockerfile: Dockerfile.test
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
        depends_on:
            - postgres
        ports:
            - 3000:3000